995 merchpage
Samfundet/Samfundet pull request #1017
Opened 2023-03-03 16:28 UTC by snorrekr

2023-03-03 16:52 UTC, snorrekr commented
#Todo
- [ ] Translation
- [ ] Review and cleanup
- [ ] Order

2023-11-07 20:28 UTC, snorrekr commented on app/abilities/ability.rb
> +    can [:new, :confirm, :create], Order
:confirm?

2023-11-07 20:32 UTC, snorrekr commented on app/assets/javascripts/product/add-to-cart.js
> +        shoppingCart.push({id: id, amount: 1, variation: selected ? {id:selected.id, name: selected.innerText} : null,  img: image.src, name: name, price: price});
Remove amount?

2023-11-07 20:39 UTC, snorrekr commented on app/assets/javascripts/product/generate-shopping-cart.js
> +    for (const order of shoppingCart) {
rename to product

2023-11-07 20:41 UTC, snorrekr commented on app/assets/javascripts/product/generate-shopping-cart.js
> +    let amountNumber = await getProducts(order.id.substring(8), order.variation ? order.variation.id.substring(4) : null);
Handle if product amount goes to zero with product in shoppingcart

2023-11-07 20:42 UTC, snorrekr commented on app/assets/javascripts/product/generate-shopping-cart.js
> +    let amountNumber = await getProducts(order.id.substring(8), order.variation ? order.variation.id.substring(4) : null);
Or deleted

2023-11-07 20:51 UTC, snorrekr commented on app/controllers/orders_controller.rb
> +          flash[:error] = 'Not enough available products'
Translation

2023-11-07 20:58 UTC, snorrekr commented on app/mailers/order_confirmation_mailer.rb
> +          reply_to: 'snorrekr@samfundet.no'
Change

2023-11-07 21:01 UTC, snorrekr commented on app/models/product_variation.rb
> +  validates :product_id, :specification, :quantity, presence: true
specifivcation -> name

2023-11-07 21:06 UTC, snorrekr commented
Add where no merche available

2023-11-07 21:07 UTC, snorrekr commented
Se på shopping-cart. Change to post

2023-11-14 20:07 UTC, snorrekr commented on app/assets/javascripts/product/add-to-cart.js
> +        shoppingCart.push({id: id, amount: 1, variation: selected ? {id:selected.id, name: selected.innerText} : null,  img: image.src, name: name, price: price});
Done

2023-11-16 19:57 UTC, robines requested changes
Bittelitt vennligere meldinger

2023-11-16 19:57 UTC, robines commented on config/locales/views/products/en.yml
> +    no_merch: No merch at the moment
```suggestion
    no_merch: There is currently no merch available
```

2023-11-16 19:57 UTC, robines commented on config/locales/views/products/no.yml
> +    no_merch: Det er for øyeblikket ikke noe merch
```suggestion
    no_merch: Det er for øyeblikket ikke noe merch tilgjengelig
```

2023-11-17 15:09 UTC, robines commented on app/assets/stylesheets/products/products.scss
> +  .product {
Kunne vi ha lagt til litt box-shadow til bilde-elementet?  Og kanskje gjøre det litt mindre? Og legge til litt mellomrom mellom Tilbake-knappen og bildet

2023-11-17 15:17 UTC, robines commented on app/views/products/index.html.haml
> +        = number_to_currency(product.price, strip_insignificant_zeros: true)
Merch som koster "20 kr" på norsk blir til "$20" på engelsk. Ikke helt riktig det

2025-03-17 17:07 UTC, robines commented
Very stale, closing

2025-03-17 17:07 UTC, closed without merging