Add rake task db:anonymize_admissions
Samfundet/Samfundet pull request #71
Opened 2016-04-15 13:33 UTC by alfiehub

Usage: `rake db:anonymize_admissions`

Improvements?

2016-04-15 15:04 UTC, aleksanb commented
How about either emptying the relevant fields, or setting them to "[REDACTED]"?

2016-04-15 15:06 UTC, aleksanb commented
It should probably take an admission to censor, that way we can access all the relevant data via @admission.applicants, .job_applications etc.

2016-04-18 18:52 UTC, aleksanb commented
We talked:
- The task should always wipe all data
- Users should be deactivated, preventing even a correct guess from logging them in
- Use faker phone number

2016-09-22 19:33 UTC, Filip0 commented on lib/tasks/db.rake
> +    Applicant.where("disabled = ?", false).each do |applicant|
You can use Applicant.where(disabled: false)

2016-09-22 19:33 UTC, Filip0 commented on lib/tasks/db.rake
> +    Interview.where("comment != ?", "").each do |interview|
Same as above

2016-09-22 19:33 UTC, Filip0 commented on lib/tasks/db.rake
> +    JobApplication.where("motivation != ?", "").each do |job_application|
Same as above

2016-09-22 19:34 UTC, Filip0 commented on app/controllers/applicant_sessions_controller.rb
> +    elsif applicant.disabled
You can filter the disabled applicants on the authenticate method

2016-09-22 19:34 UTC, Filip0 requested changes

2016-09-29 16:50 UTC, Filip0 requested changes

2016-09-29 16:50 UTC, Filip0 commented on lib/tasks/db.rake
> +    JobApplication.where(motivation: "").each do |job_application|
If motivation is blank make it blank?

2016-09-29 17:00 UTC, Filip0 approved these changes

2016-09-29 17:09 UTC, merged