[WIP] Groups page redesign
Samfundet/Samfundet pull request #786
Opened 2021-04-05 14:06 UTC by Frenje123

2021-05-02 22:59 UTC, Frenje123 commented
We would also need to create abbreviations for these groups after deploying:
* Sikringskomiteen
* S. Møller Storband
* Salongorkesteret
* Big Mama's Cowboys

2021-11-09 19:31 UTC, evgiz reviewed
ISFiT logo is stretched

2021-11-09 19:31 UTC, evgiz commented on app/views/groups/index.html.haml
> +        - t.groups.each do |g|
If number of groups with type is empty, do not render container.
Must count number of groups without pages

2021-11-09 19:39 UTC, evgiz commented
> We would also need to create abbreviations for these groups after deploying:
> 
> * Sikringskomiteen
> * S. Møller Storband
> * Salongorkesteret
> * Big Mama's Cowboys

Not necessary after changes

2021-11-09 19:54 UTC, evgiz requested changes

2021-11-09 19:54 UTC, evgiz commented on config/locales/views/groups/en.yml
> +    no_abbreviation: No known abbreviation in existance.
abbreviation exists

2021-11-09 19:54 UTC, evgiz commented on app/assets/stylesheets/groups/index.scss
> +span img { display: inline; }
remove

2021-11-09 19:56 UTC, evgiz approved these changes
Awesome<3

2021-11-09 19:57 UTC, merged

2021-11-09 19:58 UTC, oscarahalvorsen commented
closes #731
closes #732