Add shrimp fishing game to mg web application page
Samfundet/Samfundet pull request #842
Opened 2021-09-30 19:03 UTC by evgiz

Woop

2021-09-30 19:08 UTC, snorrekr requested changes

2021-09-30 19:08 UTC, snorrekr commented on app/views/jobs/show.html.haml
> +  %h1= "WEB VERV"
Remove this line

2021-09-30 19:09 UTC, evgiz commented on app/views/jobs/show.html.haml
> +  %h1= "WEB VERV"
donez

2021-11-11 18:23 UTC, snorrekr approved these changes
looks good

2021-11-11 18:23 UTC, merged