Add control panel toggle and /gesims path
Samfundet/Samfundet pull request #978
Opened 2022-10-30 19:36 UTC by evgiz

System to show "Huset er stengt" on the gesims

- Lacks translations
- Needs to implement frontend for gesims overlay

2022-10-30 19:39 UTC, emilte approved these changes

2022-11-14 20:08 UTC, snorrekr requested changes
This is just a test

2022-11-15 18:09 UTC, snorrekr approved these changes

2025-03-17 17:07 UTC, robines commented
Very stale, closing.

2025-03-17 17:07 UTC, closed without merging